application: urlaubsabrechnung
version: 1
runtime: python
api_version: 1

handlers:
- url: /admin/.*
  script: $PYTHON_LIB/apphosting/ext/admin/

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /testjs.html
  static_files: static/ext/testjs.html
  upload: static/ext/testjs.html
  
- url: /static
  static_dir: static 
  
- url: .*
  script: main.py
